version: '2'

services:

  engine:
    build: automation/docker/drupal
    links:
      - mysql
    volumes:
      - ./src/modules/:/var/www/html/modules
      - ./src/profiles/:/var/www/html/profiles
      - ./src/themes/:/var/www/html/themes
      # this takes advantage of the feature in Docker that a new anonymous
      # volume (which is what we're creating here) will be initialized with the
      # existing content of the image at the same location
      #- ./src/sites/:/var/www/html/sites
    labels:
      - "traefik.enable=false"

  front:
    build: automation/docker/front
    links:
      - engine
    volumes_from:
      - engine
    labels:
      - "traefik.backend=nginx"
      - "traefik.frontend.rule=Host:drupal.docker.localhost"
      - "traefik.port=80"
      - "traefik.frontend.entryPoints=http"

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    volumes:
      - ./var/mysql:/var/lib/mysql
    labels:
      - "traefik.enable=false"

networks:
    default:
        external:
            name: proxy_default
