#!/bin/bash

set -e

source ./automation/vars/mysql

# Build docker images
docker-compose build

# Start docker containers
docker-compose up -d --force-recreate

# Waiting for mysql service ready
echo "Waiting for mysql service ready..."
while ! docker-compose exec engine mysqladmin ping -h"$DB_HOST" -u"DB_USER" -p"DB_PASSWORD" --silent; do
    sleep 1
done

docker-compose exec engine /var/www/automation/bin/install
